name: Node.js CI (SmartBuy Testing)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Backend Dependencies
      # Agar aapka folder name 'backend' hai toh ye chalega
      run: npm install
      working-directory: ./backend 

    - name: Build Project
      run: npm run build --if-present
      working-directory: ./backend